const $=id=>document.getElementById(id);
const words={"신조어": ["꿀잼", "노잼", "최애", "득템", "찐친", "인싸", "갓생", "먹방", "금손", "웃프다", "심쿵", "소확행", "댕댕이", "꿀맛", "킹받다"], "외국어": ["Thank you", "Good morning", "Sorry", "See you", "Happy birthday", "Welcome", "Good job", "Let’s go", "Please", "Congratulations", "Hello", "Good night", "땡큐"], "외래어": ["스케줄", "리뷰", "이벤트", "미팅", "테이크아웃", "리더", "챌린지", "메시지", "아이디어", "팀", "타이틀", "베스트", "패스", "스터디", "체크", "디저트", "스킵", "노트", "댄스", "스타일"], "줄임말": ["생파", "문상", "아아", "갑분싸", "점메추", "저메추", "꾸안꾸", "얼죽아", "단톡방", "비번", "프사", "복붙", "혼밥", "열공", "노답", "스포", "멘붕"], "아파트 이름": ["아크로 리버파크", "아크로 서울포레스트", "아크로 리버뷰", "아크로 타워스퀘어", "아크로 힐스논현", "힐스테이트 레이크 송도", "리버", "파크", "포레스트", "레이크", "스카이", "센트럴"]};
const meanings={"꿀잼": "아주 재미있다는 뜻", "노잼": "재미가 없다는 뜻", "최애": "가장 좋아하는 대상", "득템": "마음에 드는 물건을 얻음", "찐친": "아주 가까운 친구", "인싸": "여러 사람과 잘 어울리는 사람", "갓생": "부지런하고 계획적으로 사는 생활", "먹방": "음식을 먹는 모습을 보여 주는 방송", "금손": "만들기나 그림 등을 아주 잘하는 사람", "웃프다": "웃기면서도 슬프다는 뜻", "심쿵": "놀라거나 설레어 가슴이 두근거림", "소확행": "작지만 확실하게 느끼는 행복", "Thank you": "감사를 전하는 영어 인사", "Good morning": "아침에 하는 영어 인사", "Sorry": "미안한 마음을 전하는 영어 표현", "See you": "헤어질 때 다음 만남을 기약하는 영어 인사", "Happy birthday": "생일을 축하하는 영어 표현", "Welcome": "반갑게 맞이하는 영어 표현", "Good job": "잘한 일을 칭찬하는 영어 표현", "Let’s go": "함께 가자고 하는 영어 표현", "Please": "부탁할 때 쓰는 영어 표현", "Congratulations": "축하할 때 쓰는 영어 표현", "Hello": "만났을 때 하는 영어 인사", "Good night": "밤에 잠자리에 들 때 하는 영어 인사", "스케줄": "해야 할 일과 시간을 정한 계획", "리뷰": "책·영화·물건 등을 보고 느낀 점이나 평가", "이벤트": "특별히 마련한 행사", "미팅": "사람들이 만나 이야기하는 모임", "테이크아웃": "음식이나 음료를 가게 밖으로 가져가는 것", "리더": "모임이나 활동을 이끄는 사람", "챌린지": "어떤 목표나 과제에 도전하는 활동", "메시지": "다른 사람에게 전하는 말이나 글", "아이디어": "어떤 일을 위한 생각이나 방법", "팀": "같은 일을 함께 하는 사람들의 모임", "타이틀": "책·영화·작품 등에 붙인 이름", "베스트": "가장 좋거나 뛰어나다는 뜻", "생파": "생일 파티를 줄인 말", "문상": "문화 상품권을 줄여 부르는 말", "아아": "아이스 아메리카노를 줄인 말", "갑분싸": "갑자기 분위기가 싸늘해진다는 말을 줄임", "점메추": "점심 메뉴 추천을 줄인 말", "저메추": "저녁 메뉴 추천을 줄인 말", "꾸안꾸": "꾸민 듯 안 꾸민 듯을 줄인 말", "얼죽아": "얼어 죽어도 아이스 음료라는 말을 줄임", "단톡방": "단체 대화방을 줄여 부르는 말", "비번": "비밀번호를 줄인 말", "프사": "프로필 사진을 줄인 말", "복붙": "복사해서 붙여 넣기를 줄인 말", "댕댕이": "강아지를 재미있게 부르는 말", "꿀맛": "아주 맛있다는 뜻", "킹받다": "매우 화나거나 짜증이 난다는 뜻", "땡큐": "감사를 전하는 영어 thank you를 소리 나는 대로 쓴 말", "패스": "공 등을 다른 사람에게 넘기는 것", "스터디": "공부하거나 공부하기 위해 모이는 활동", "체크": "맞는지 살펴보고 확인하는 것", "디저트": "식사 뒤에 먹는 음식", "스킵": "어떤 순서나 일을 건너뛰는 것", "노트": "글을 적는 공책", "댄스": "음악이나 장단에 맞추어 몸을 움직이는 춤", "스타일": "모습·방식·취향 등을 가리키는 말", "혼밥": "혼자 밥 먹기를 줄인 말", "열공": "열심히 공부하기를 줄인 말", "노답": "영어 no와 답을 결합한 말로, 답이나 해결 방법이 없다는 뜻", "스포": "줄거리나 결말을 미리 알리는 스포일러를 줄인 말", "멘붕": "멘탈 붕괴를 줄인 말로, 몹시 당황하거나 혼란스러운 상태", "아크로 리버파크": "실제 아파트 이름이에요. 리버(river)는 강, 파크(park)는 공원을 뜻해요. 강과 공원을 떠올리며 새 이름을 지어 보세요.", "아크로 서울포레스트": "실제 아파트 이름이에요. 포레스트(forest)는 숲을 뜻해요. 서울과 숲을 떠올리며 우리말 이름을 지어 보세요.", "아크로 리버뷰": "실제 아파트 이름이에요. 리버(river)는 강, 뷰(view)는 보이는 경치라는 뜻이에요. 강이 보이는 풍경을 떠올려 보세요.", "아크로 타워스퀘어": "실제 아파트 이름이에요. 타워(tower)는 탑이나 높은 건물, 스퀘어(square)는 광장 등의 뜻이에요. 느낌을 살려 이름을 지어 보세요.", "아크로 힐스논현": "실제 아파트 이름이에요. 힐스(hills)는 언덕들이라는 뜻이에요. 논현은 지역 이름이에요. 언덕을 떠올려 이름을 지어 보세요.", "힐스테이트 레이크 송도": "실제 아파트 이름이에요. 레이크(lake)는 호수를 뜻해요. 송도는 지역 이름이에요. 호수를 떠올리며 새 이름을 지어 보세요.", "리버": "이름 속 영어 표현 river. 강을 뜻해요.", "파크": "이름 속 영어 표현 park. 공원을 뜻해요.", "포레스트": "이름 속 영어 표현 forest. 숲을 뜻해요.", "레이크": "이름 속 영어 표현 lake. 호수를 뜻해요.", "스카이": "이름에 쓰이는 영어 표현 sky. 하늘을 뜻해요.", "센트럴": "이름에 쓰이는 영어 표현 central. 중심의, 중앙의라는 뜻이에요."};
const categoryDescriptions={"신조어": "새롭게 만들어져 쓰이는 말이에요. 줄임말과 겹치는 말도 있어요.", "외국어": "다른 나라의 언어로 된 표현이에요. 여기서는 영어 인사와 생활 표현을 살펴봐요.", "외래어": "다른 나라에서 들어와 우리말처럼 쓰이는 말이에요. 모두 틀린 말은 아니에요.", "줄임말": "긴 말의 일부를 줄여 만든 말이에요. 모르는 사람에게는 뜻을 풀어 말해 보세요.", "아파트 이름": "외국어 표현이 들어간 실제 아파트 이름과 이름 속 낱말이에요. 지명·브랜드 이름도 섞여 있어요. 공식 이름을 번역하는 정답은 없어요. 풍경이나 느낌을 살려 나만의 우리말 이름을 지어 보세요."};
const exampleSentences={"꿀잼": "오늘 수업 꿀잼!", "패스": "공 패스해 줘!", "심쿵": "귀여워서 심쿵했어!", "땡큐": "숙제 도와줘서 땡큐!", "댕댕이": "우리 집 댕댕이", "스터디": "친구랑 스터디했어.", "혼밥": "오늘은 혼밥할래.", "열공": "오늘 열공하자!", "노답": "이 문제는 노답이야.", "체크": "정답 체크하자.", "꿀맛": "오늘 급식 꿀맛!", "디저트": "디저트 배는 따로지!", "스포": "스포하지 마!", "스킵": "아침밥은 스킵하자.", "노잼": "영화가 노잼이야.", "노트": "노트 좀 빌려 줄래?", "스케줄": "스케줄이 어떻게 돼?", "멘붕": "갑자기 멘붕이야.", "댄스": "어제 댄스 연습했어.", "킹받다": "엄청 킹받아.", "스타일": "내 스타일이야!"};
const nameSources={"아크로 리버파크": "https://www.acro.co.kr/MPosm_main.action?commonMap.CD_BIZ_LND=010366", "아크로 서울포레스트": "https://www.acro.co.kr/MMnmn_footerSitemap.action", "아크로 리버뷰": "https://www.acro.co.kr/MMnmn_footerSitemap.action", "아크로 타워스퀘어": "https://www.acro.co.kr/MMnmn_footerSitemap.action", "아크로 힐스논현": "https://www.acro.co.kr/MMnmn_footerSitemap.action", "힐스테이트 레이크 송도": "https://lshill.aptner.com/v2/page/menu/1121"};
function wordTab(cat){$('categoryHelp').textContent=categoryDescriptions[cat];$('wordMeaning').textContent='낱말을 누르면 뜻과 쓰임을 확인할 수 있어요.';$('nameSource').hidden=true;$('words').replaceChildren();for(const word of words[cat]){let b=document.createElement('button');b.textContent=word;b.title=meanings[word];b.onclick=()=>{$('original').value=word;$('category').value=cat;$('wordMeaning').textContent=word+' · '+meanings[word]+(exampleSentences[word]?'\n문장 속 쓰임: '+exampleSentences[word]:'');$('nameSource').hidden=!nameSources[word];if(nameSources[word])$('nameSource').href=nameSources[word];$('replacement').focus()};$('words').append(b)}for(const b of $('wordFilters').children)b.classList.toggle('active',b.textContent===cat)}
for(const cat of Object.keys(words)){let b=document.createElement('button');b.textContent=cat;b.onclick=()=>wordTab(cat);$('wordFilters').append(b)}wordTab('신조어');

const KEY='bareunmal-personal-v1';
let notes=[];try{notes=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(notes))notes=[];notes=notes.filter(n=>n.category!=='거친 말').map(({group,...n})=>n)}catch{notes=[]}
function status(msg,error=false){$('status').textContent=msg;$('status').classList.toggle('error',error)}
function elt(tag,txt,cls){const e=document.createElement(tag);e.textContent=txt;if(cls)e.className=cls;return e}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(notes));render();return true}catch{render();status('이 브라우저에 저장하지 못했어요. 창을 닫기 전에 사전 이미지를 다운로드해 주세요.',true);return false}}
function showDetail(n){$('detailBody').replaceChildren(elt('p',n.category),elt('p',n.original+' →'),elt('h3',n.replacement),elt('p','바꾼 까닭\n'+n.reason),elt('p',n.sentence?'사용 문장\n'+n.sentence:''),elt('p',n.name));$('detail').showModal()}
function render(){let q=$('search').value.trim().toLowerCase();let list=notes.filter(n=>(!$('filter').value||n.category===$('filter').value)&&(!$('starOnly').checked||n.star)&&[n.original,n.replacement,n.reason,n.name,n.sentence].join(' ').toLowerCase().includes(q));$('count').textContent=notes.length;$('notes').replaceChildren();if(!list.length)$('notes').append(elt('div',notes.length?'검색 조건에 맞는 포스트잇이 없어요.':'첫 번째 우리말 포스트잇을 붙여 보세요!','empty'));for(const n of list){let card=elt('article','','note '+n.color),b=elt('button','','open');b.append(elt('small',(n.star?'★ 내가 고른 말 · ':'')+n.category),elt('div',n.original+' →','old'),elt('h3',n.replacement),elt('div',n.reason,'reason'),elt('div',n.name,'meta'));b.onclick=()=>showDetail(n);let a=elt('div','','actions'),star=elt('button',n.star?'선택 해제':'★ 마음에 드는 말'),edit=elt('button','수정'),del=elt('button','삭제');star.onclick=()=>{n.star=!n.star;persist()};edit.onclick=()=>{for(const id of ['name','category','original','replacement','reason','sentence','color'])$(id).value=n[id];if(n.category==='외국어·외래어')$('category').value='외래어';$('form').dataset.edit=n.id;$('submit').textContent='포스트잇 수정 완료 ↗';$('student').scrollIntoView({behavior:'smooth'});$('original').focus()};del.onclick=()=>{if(!confirm('이 포스트잇을 삭제할까요?'))return;notes=notes.filter(x=>x.id!==n.id);if($('form').dataset.edit===n.id){delete $('form').dataset.edit;$('submit').textContent='내 사전에 붙이기 ↗'}persist()};a.append(star,edit,del);card.append(b,a);$('notes').append(card)}}
$('dismiss').onclick=()=>$('detail').close();for(const id of ['search','filter','starOnly'])$(id).oninput=render;
$('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{status('이 기기에서는 전체화면을 사용할 수 없어요.',true)}};
$('form').onsubmit=e=>{e.preventDefault();let n={};for(const id of ['name','category','original','replacement','reason','sentence','color'])n[id]=$(id).value.trim();if(!n.name||!n.original||!n.replacement||!n.reason)return status('이름, 낱말, 바꾼 말, 까닭을 채워 주세요.',true);const editing=$('form').dataset.edit;if(!editing&&notes.length>=40)return status('한 사전에는 40개까지 담을 수 있어요. 수정하거나 이미지를 저장해 주세요.',true);if(editing){let index=notes.findIndex(x=>x.id===editing);if(index>=0)notes[index]={...notes[index],...n};delete $('form').dataset.edit}else notes.push({...n,id:crypto.randomUUID(),star:false});const saved=persist();for(const id of ['original','replacement','reason','sentence'])$(id).value='';$('submit').textContent='내 사전에 붙이기 ↗';if(saved)status('내 사전에 붙였어요! 다 만들면 사전 이미지 다운로드를 눌러 주세요.')};
const colors={yellow:'#fff0ac',pink:'#f9dce2',green:'#dcebc8',blue:'#d7e8f3'};
function lines(ctx,text,max){let out=[],line='';for(const ch of String(text)){if(ch==='\n'){out.push(line);line='';continue}if(ctx.measureText(line+ch).width>max&&line){out.push(line);line=ch}else line+=ch}out.push(line);return out}
function textBlock(ctx,text,x,y,width,size=26,color='#35483c',bold=false){ctx.font=(bold?'700 ':'400 ')+size+'px "Noto Sans KR", sans-serif';ctx.fillStyle=color;const wrapped=lines(ctx,text,width);for(const line of wrapped){ctx.fillText(line,x,y);y+=size*1.5}return y}
$('download').onclick=async()=>{if(!notes.length)return status('포스트잇을 한 장 이상 만든 뒤 다운로드해 주세요.',true);const button=$('download');button.disabled=true;button.textContent='이미지 만드는 중…';try{await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1600;const ctx=canvas.getContext('2d');const width=660;let plans=notes.map(n=>{let h=145;for(const [text,size] of [[n.original+' →',26],[n.replacement,36],['바꾼 까닭: '+n.reason,25],...(n.sentence?[['사용 문장: '+n.sentence,25]]:[])]){ctx.font=size+'px "Noto Sans KR", sans-serif';h+=lines(ctx,text,width).length*size*1.5+16}return {n,h:Math.max(340,h)}});let y=340;for(let i=0;i<plans.length;i+=2){let h=Math.max(plans[i].h,plans[i+1]?.h||0);plans[i].x=60;plans[i].y=y;if(plans[i+1]){plans[i+1].x=820;plans[i+1].y=y}y+=h+42}canvas.height=y+130;ctx.fillStyle='#faf7ef';ctx.fillRect(0,0,1600,canvas.height);ctx.textBaseline='top';textBlock(ctx,'우리말 꽃밭 · 바른말 대체 사전',60,52,1160,52,'#365c47',true);const names=[...new Set(notes.map(n=>n.name))].join(' · ');textBlock(ctx,names.length>110?names.slice(0,110)+'…':names,60,142,1200,25);textBlock(ctx,'누구나 이해하기 쉬운 말로, 마음이 통하도록!',60,230,1250,28);try{const img=new Image();img.src=$('sejong').src;await img.decode();ctx.drawImage(img,1310,32,245,185)}catch{}for(const {n,h,x,y} of plans){ctx.fillStyle=colors[n.color]||colors.yellow;ctx.beginPath();ctx.roundRect(x,y,720,h,12);ctx.fill();ctx.fillStyle='#ffffff88';ctx.fillRect(x+280,y-8,140,25);let ty=y+38;ty=textBlock(ctx,n.category+(n.star?' · ★ 내가 고른 말':''),x+30,ty,width,21,'#617354')+18;ty=textBlock(ctx,n.original+' →',x+30,ty,width,26,'#746e5b')+12;ty=textBlock(ctx,n.replacement,x+30,ty,width,36,'#304d3c',true)+14;ty=textBlock(ctx,'바꾼 까닭: '+n.reason,x+30,ty,width,25)+12;if(n.sentence)ty=textBlock(ctx,'사용 문장: '+n.sentence,x+30,ty,width,25)+12;textBlock(ctx,n.name,x+30,y+h-44,width,21,'#617354')}textBlock(ctx,'우리말을 바르게 쓰면 뜻을 잘 전달하고 서로를 배려할 수 있어요.  |  총 '+notes.length+'개',60,canvas.height-80,1480,23);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('이미지 생성 실패');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='우리말사전_'+(notes[0].name||'나의사전').replace(/[\\/:*?"<>|]/g,'')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);status('사전 전체를 한 장의 PNG 이미지로 저장했어요. 다운로드 폴더를 확인해 주세요. 검색 필터와 관계없이 모든 포스트잇이 들어갑니다.')}catch(e){console.error(e);status('이미지를 만들지 못했어요. 포스트잇 수를 줄이거나 다른 브라우저에서 다시 시도해 주세요.',true)}finally{button.disabled=false;button.textContent='사전 이미지 다운로드 ↓'}};
render();status('로그인 없이 사용해요. 내 사전은 이 브라우저에 저장되고, 완성본은 이미지로 다운로드할 수 있어요.');
